on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install goose
        run: go build \
          -tags='no_postgres no_clickhouse no_mssql no_mysql' \
          -o goose ./cmd/goose

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"
          cache: true

      - name: Run go tests
        run: go test ./...

      - name: build app
        run: scripts/buildprod.sh

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info

      - name: Build and push docker image
        run: gcloud builds submit --tag europe-west1-docker.pkg.dev/notely-463506/notely-ar-repo/notely:latest .

      - name: Run DB migration
        run: ./scripts/migrateup.sh

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image europe-west1-docker.pkg.dev/notely-463506/notely-ar-repo/notely:latest --region europe-west1 --allow-unauthenticated --project notely-463506 --max-instances=4
